# Generated by Django 2.1 on 2018-08-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_texts',
            new_name='choice_text',
        ),
    ]
