# Generated by Django 2.1 on 2018-08-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180820_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ques_text',
            new_name='ques_texts',
        ),
    ]
