# Generated by Django 2.1 on 2018-08-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180828_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ques_texts',
            new_name='ques_text',
        ),
    ]
